### ISSUE TITLE
Wrong Login Credentials

### ISSUE THREAD

**Issue by stevangoldduck** [forddyce/mlm-1#1]
The login credentials u wrote is wrong, it's always return Username/Password doesn't match

**Comment by stevangoldduck** [comment]
i've tried all, nothings happen

**Comment by forddyce** [comment]
There are people who can set this up correctly. If you can't you probably
did something wrong.

**Comment by forddyce** [comment]
Post your content of `vendor/cartalyst/sentinel/src/Users/EloquentUser.php`

**Comment by stevangoldduck** [comment]
i've changed it, maybe you can add more details in README. It's work, i'm gonna close it
